config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
            path: '',
            path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
            controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :host_reviews, only: [:create, :destroy]
  resources :guest_reviews, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/views/shared/_contact_form.html.erb
<div class="contact-form">
      <div class="form-items">
        <%= form_for Contact.new, url: contacts_path do |f| %>
          <div class="form-group">
            <%= f.text_field :name, class: "form-input", :id=> "name", placeholder: "full name" %>
            <label for="name" class="form-label">full name</label>
          </div>

          <div class="form-group">
            <%= f.email_field :email, class: "form-input", :id=> "email", placeholder: "email address" %>
            <label for="email" class="form-label">email address</label>
          </div>
          
          <div class="form-group">
            <%= f.text_area :message, class: "msg-box", rows: 8, :id=> "message", placeholder: "type your message here" %>
          </div>

          <div class="form-group">
            <button class="butn butn--blue">Send Message</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_devise_messages.html.erb
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |value| %>
      toastr.error('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_messages.html.erb
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |key, value| %>
      <% type = key.to_s.gsub('alert', 'error').gsub('notice', 'success') %>
      toastr['<%= type %>']('<%= value %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sleep-INN", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
       <div class="form-group">
         <%= text_field_tag :search, params[:search], placeholder: "Start Your Search", class: "form-control search-field" %>
       </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        <li>
          <button class="btn btn-facebook btn-small">
            <%= link_to "Become a Host", new_room_path, style: "color: white; text-decoration: none;" %>
          </button>
        </li>
        <% if (!user_signed_in?) %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a
              href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
              aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user, 150, 150), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Manage Listing", rooms_path %></li>
              <li><%= link_to "List Your Space", new_room_path %></li>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <li><%= link_to "Your Trips", your_trips_path %></li>

              <li role="separator" class="divider"></li>
              <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/views/shared/_popup.html.erb
<div class="popup">
  <div class="popup-content">
    <div class="popup-left">
      <%= image_tag "heniu.jpg", width: 150, alt: "popup image", class: 'popup-img' %>
    </div>
    <div class="popup-right">
      <p class="popup-text">Thank you very much for your message!<br/><br/> I'll get back to you shortly &#128522</p>
      <%= link_to root_path do %>
        <span class="popup-close">&times;</span>
      <% end %>
    </div>
  </div>
</div>