config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for :users,
            path: '',
            path_names: {sign_in: 'login', sign_out: 'logout', edit: 'profile', sign_up: 'registration'},
            controllers: {omniauth_callbacks: 'omniauth_callbacks', registrations: 'registrations'}

  resources :users, only: [:show]
  resources :rooms, except: [:edit] do
    member do
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
      get 'amenities'
      get 'location'
      get 'preload'
      get 'preview'
    end
    resources :photos, only: [:create, :destroy]
    resources :reservations, only: [:create]
  end

  resources :host_reviews, only: [:create, :destroy]
  resources :guest_reviews, only: [:create, :destroy]
  resources :contacts, only: [:new, :create]

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'
  get 'search' => 'pages#search'
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos
  has_many :reservations
  has_many :guest_reviews

  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accomodate, presence: true
  validates :bed_room, presence: true
  validates :bath_room, presence: true

  def cover_photo(size)
    if self.photos.length > 0
      self.photos[0].image.url(size)
    else
      "blank.jpg"
    end
  end

  def average_rating
    guest_reviews.count == 0 ? 0 : guest_reviews.average(:star).round(2).to_i
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_room, except: [:index, :new, :create]
  before_action :authenticate_user!, except: [:show]
  before_action :is_authorized, only: [:listing, :pricing, :photo_upload, :description, :amenities, :location, :update]

  def index
    @rooms = current_user.rooms
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      flash[:notice] = "Your space has been successfully created!"
      redirect_to listing_room_path(@room)
    else
      flash[:alert] = "Something went wrong while creating your space. Please try again!"
      render 'new'
    end
  end

  def show
    @photos = @room.photos
    @guest_reviews = @room.guest_reviews
  end

  def listing

  end

  def pricing
  end

  def description
  end

  def photo_upload
    @photos = @room.photos
  end

  def amenities
  end

  def location
  end

  def update
    new_params = room_params

    #if room is active, merge the new room params with the active param with a value of true
    new_params = room_params.merge(active: true) if is_ready_room
    if @room.update(new_params)
      flash[:notice] = "Saved"
    else
      flash[:alert] = "Something went wrong"
    end
      redirect_back(fallback_location: request.referer)
  end

  # --Reservations --
  # get all start and end dates of all room reservations and pass to datepicker as json
  def preload
    today = Date.today
    reservations = @room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

    render json: reservations
  end

  # get reservation start_date and end_date and pass into the is_conflict to check
  # if those reservation dates are available
  def preview
    start_date = Date.parse(params[:start_date])
    end_date = Date.parse(params[:end_date])

    output = {
      conflict: is_conflict(start_date, end_date, @room)
    }

    render json: output
  end

  private

  # check if room is already booked
  def is_conflict(start_date, end_date, room)
    check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
    check.size > 0 ? true : false
  end

  def set_room
    @room = Room.find(params[:id])
  end

  def is_authorized
    redirect_to root_path, alert: "You don't have permission to perform this action" unless current_user.id == @room.user_id
  end

  def is_ready_room
    !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank?
  end

  def room_params
    #set which room attribute a user can create, update or change
    params.require(:room).permit(:home_type, :room_type, :accomodate, :bed_room,
      :bath_room, :listing_name, :summary, :address, :is_tv, :is_kitchen, :is_air,
      :is_heating, :is_internet, :price, :active)
  end

end

app/helpers/room_helper.rb
module RoomHelper
end

app/views/rooms/_room_menu.html.erb
<ul class="sidebar-link">
  <li class="sidebar-item">
    <%= link_to "Listing", listing_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Pricing", pricing_room_path, class: "sidebar-link active" %>
    <% if !@room.price.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Description", description_room_path, class: "sidebar-link active" %>
    <% if !@room.listing_name.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Photos", photo_upload_room_path, class: "sidebar-link active" %>
    <% if !@room.photos.blank? %>
      <span id="photo_check", class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
  <li class="sidebar-item">
    <%= link_to "Amenities", amenities_room_path, class: "sidebar-link active" %>
    <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
  </li>
  <li class="sidebar-item">
    <%= link_to "Location", location_room_path, class: "sidebar-link active" %>
    <% if !@room.address.blank? %>
      <span class="pull-right text-babu"><i class="fa fa-check"></i></span>
    <% end %>
  </li>
</ul>
<hr/>

<% is_ready = !@room.active && !@room.price.blank? && !@room.listing_name.blank? && !@room.photos.blank? && !@room.address.blank? %>
<%= form_for @room do |f| %>
  <%= f.hidden_field :active, value: true %>
  <%= f.submit "Publish", id: "publish_button", class: "btn btn-normal btn-block", disabled: !is_ready %>
<% end %>

app/views/rooms/_rooms_list.html.erb
<% rooms.each do |room| %>
  <div class="feature-box">
    <div class="col-md-3">
      <div class="panel panel-default">
        <div class="panel-heading preview">
          <%= image_tag room.cover_photo(:medium) %>
        </div>
        <div class="panel-body">
          <%= link_to room.listing_name, room %><br/>
          $<%= room.price %> - <%= room.home_type %> - <%= pluralize(room.bed_room, "bed") %>
          <div id="star_<%= room.id %>"></div> <%= pluralize(room.average_rating, "review") %>
        </div>
      </div>
    </div>
  </div>

  <script>
    $('#star_<%= room.id %>').raty({
      path: '/assets',
      readOnly: true,
      score: <%= room.average_rating %>
    });
  </script>
<% end %>

app/views/rooms/amenities.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Amenities
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row form-group">

              <div class="col-md-4 text-babu">
                <%= f.check_box :is_tv? %> Television
              </div>

              <div class="col-md-4 text-babu">
                <%= f.check_box :is_kitchen? %> Kitchen
              </div>

              <div class="col-md-4 text-babu">
                <%= f.check_box :is_internet? %> Internet
              </div>

            </div>

            <div class="row form-group">

              <div class="col-md-4 text-babu">
                <%= f.check_box :is_heating? %> Heating
              </div>

              <div class="col-md-4 text-babu">
                <%= f.check_box :is_air? %> Air Conditioning
              </div>

            </div>

            <br/><br/>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-normal" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/create.html.erb
<h1>Room#create</h1>
<p>Find me in app/views/room/create.html.erb</p>

app/views/rooms/description.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Description
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

          <div class="row">
            <div class="form-group">
              <label class="text-babu">Name of Listing</label>
              <%= f.text_field :listing_name, placeholder: "Listing Name", class: "form-control", required: true %>
            </div>
          </div>

          <div class="row">
            <div class="form-group">
              <label class="text-babu">Description</label>
              <%= f.text_field :summary, rows: 5, placeholder: "Describe your listing", class: "form-control", required: true %>
            </div>
          </div>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-normal" %>
          </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
      <li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
      <li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
    </ul>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Listings
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
          <div class="row panel-content">
            <div class="col-md-2">
              <%= image_tag room.cover_photo(:thumb) %>
            </div>
            <div class="col-md-7">
              <h4><%= link_to room.listing_name, room_path(room)  %></h4>
            </div>
            <div class="col-md-3 right">
              <%= link_to "Update", listing_room_path(room), class: "btn btn-normal" %>
            </div>
          </div>
          
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/listing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Listing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>
            <div class="row">

              <div class="col-md-4 select">
                <div class="form-group">
                  <label class="text-babu">Home Type</label>
                  <%= f.select :home_type,[["Apartment, Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                                id: "home_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label class="text-babu">Room Type</label>
                  <%= f.select :room_type,[["Entire, Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                                id: "room_type", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label class="text-babu">Accomodate</label>
                  <%= f.select :accomodate,[["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "accomodate", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label class="text-babu">Bedrooms</label>
                  <%= f.select :bed_room,[["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bed_room", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

              <div class="col-md-4 select">
                <div class="form-group">
                  <label class="text-babu">Bathrooms</label>
                  <%= f.select :bath_room, [["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                                id: "bath_room", prompt: "Select...", class: "form-control" %>
                </div>
              </div>

            </div>
            <div><%= f.submit "Save", class: "btn btn-normal" %></div>
          <% end %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/location.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Location
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

            <div class="row">
              <div class="form-group">
                <label class="text-babu">Address</label>
                <%= f.text_field :address, placeholder: "What is your address?", class: "form-control", required: true, id: "autoaddress" %>
              </div>
            </div>

            <div class="text-center">
              <%= f.submit "Save", class: "btn btn-normal" %>
            </div>

          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

<script>
  $(function () {
    $("#autoaddress").geocomplete();
  });
</script>

app/views/rooms/new.html.erb
<div class="panel panel-default">
  <div class="panel panel-heading">
    Create your beautiful place
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @room do |f| %>
        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label class="text-babu", style="padding-right: .5rem;">Home Type</label>
              <%= f.select :home_type,[["Apartment", "Apartment"], ["House", "House"], ["Bed & Breakfast", "Bed & Breakfast"]],
                            id: "home_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label class="text-babu", style="padding-right: .5rem;">Room Type</label>
              <%= f.select :room_type,[["Entire", "Entire"], ["Private", "Private"], ["Shared", "Shared"]],
                            id: "room_type", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label class="text-babu", style="padding-right: .5rem;">Accomodate</label>
              <%= f.select :accomodate,[["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "accomodate", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label class="text-babu", style="padding-right: .5rem;">Bedrooms</label>
              <%= f.select :bed_room,[["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bed_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label class="text-babu", style="padding-right: .5rem;">Bathrooms</label>
              <%= f.select :bath_room,[["1", 1], ["2", 2], ["3", 3], ["4+", 4]],
                            id: "bath_room", prompt: "Select...", class: "form-control" %>
            </div>
          </div>

        </div>
        <div><%= f.submit "Create Room", class: "btn btn-normal" %></div>
      <% end %>

    </div>
  </div>
</div>

app/views/rooms/photo_upload.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Photos
      </div>

      <div class="panel-body">
        <div class="container">
          <div class="row">
            <div class="col-md-6 col-md-offset-3">
              <%= form_for @room, url: room_photos_path(@room), method: 'post', html: {multipart: true} do |f| %>
                <div class="row">
                  <div class="form-group">
                    <span class="btn btn-default btn-file text-babu">
                      <i class="fa fa-cloud-upload" aria-hidden="true"></i> Select Photos
                      <%= file_field_tag "images[]", type: :file, multiple: true %>
                    </span>
                  </div>
                </div>
                <div class="text-center">
                  <%= f.submit "Add Photos", class: "btn btn-normal" %>
                </div>
              <% end %>
            </div>
          </div>
          <div id="photos">
            <%= render 'photos/photos_list' %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/pricing.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render 'room_menu' %>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">

      <div class="panel-heading">
        Pricing
      </div>

      <div class="panel-body">
        <div class="container">
          <%= form_for @room do |f| %>

          <div class="row">
            <div class="form-group">
              <label class="text-babu">Price</label>
              <%= f.text_field :price, placeholder: "eg: 200", class: "form-control", required: true %>
            </div>
          </div>

          <div class="text-center">
            <%= f.submit "Save", class: "btn btn-normal" %>
          </div>

          <% end %>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/rooms/show.html.erb
<!-- Image -->
<div class="row">
  <div class="col-md-12">
    <%= image_tag @room.cover_photo(nil), width: "100%" %>
  </div>
</div>
<br/>

<div class="row">

  <!-- LEFT PANEL -->
  <div class="col-md-8">

    <!-- Listing name -->
    <div class="row">
      <div class="col-md-8">
        <h1 class="listing-name"><%= @room.listing_name %></h1>
        <%= @room.address %>
      </div>
      <div class="col-md-4 text-center">
        <%= image_tag avatar_url(@room.user), class: "img-circle avatar-large" %><br/><br/>
        <%= @room.user.fullname %>
      </div>

    </div>

    <!-- Room Info -->
    <div class="row text-babu">
      <div class="row text-center row-space-1">
        <div class="col-md-3">
          <i class="fa fa-home fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-user-circle-o fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bed fa-2x"></i>
        </div>
        <div class="col-md-3">
          <i class="fa fa-bath fa-2x"></i>
        </div>
      </div>

      <div class="row text-center">
        <div class="col-md-3"><%= @room.home_type %></div>
        <div class="col-md-3"><%= pluralize(@room.accomodate, "Guest") %></div>
        <div class="col-md-3"><%= pluralize(@room.bed_room, "Bedroom") %></div>
        <div class="col-md-3"><%= pluralize(@room.bath_room, "Bathroom") %></div>
      </div>
    </div>

    <!-- About -->
    <div class="row about-listing">
      <h3 class="listing-title">About this Listing</h3>
      <p><%= @room.summary %></p>
    </div>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-3">
        <h4 class="listing-title">Amenities</h4>
      </div>

      <div class="col-md-9">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_tv %>">Televison</li>
              <li class="<%= 'text-line-through' if !@room.is_kitchen %>">Kitchen</li>
              <li class="<%= 'text-line-through' if !@room.is_internet %>">Internet</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'text-line-through' if !@room.is_heating %>">Heating</li>
              <li class="<%= 'text-line-through' if !@room.is_tv %>">Air Conditioning</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <hr/>

    <!-- Carousel -->
    <div class="row room-photos">
      <% if @photos.length > 0 %>
        <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
          <% @photos.each do |photo| %>
            <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"</li>
            <% end %>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner">
          <% @photos.each do |photo| %>
            <div class="item <%= 'active' if photo.id == @photos[0].id %>">
              <%= image_tag photo.image.url() %>
            </div>
          <% end %>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" data-slide="prev">
          <span class="glyphicon glyphicon-chevron-left"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" data-slide="next">
          <span class="glyphicon glyphicon-chevron-right"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>
      <% end %>
    </div>
    <hr/>

    <!-- REVIEWS -->
    <div class="row">
      <div class="col-md-12">
        <h3 class="listing-title">
          <%= pluralize(@guest_reviews.count, "Review" ) %>
          <span id="average_rating"></span>
        </h3>
        <div class="container">
          <div>
            <%= render 'reviews/guest_list' %>
          </div>
        </div>
      </div>
    </div>
    <br/>
    <hr/>

    <!-- GOOGLE MAP -->
    <div class="row room-map">
      <div id="map" style="width: 100%; height: 450px"></div>
        <script>
          let map;
          function initMap() {
            let location = {lat: <%= @room.latitude %>, lng: <%= @room.longitude %>};

            map = new google.maps.Map(document.getElementById('map'), {
              center: location,
              zoom: 8
            });

            var marker = new google.maps.Marker({position: location, map: map});

            var infoWindow = new google.maps.InfoWindow({
              content: '<div id="content"><%= image_tag @room.cover_photo(:medium) %></div>'
            });
            infoWindow.open(map, marker);
          }
        </script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVwlqxKonOYIzb3CwWLxxWBMZYbAEa4GE&callback=initMap"
        async defer></script>

    </div>

    <!-- NEAR BY ROOMS -->
    <div class="row near-by">
      <h3 class="sub-heading">NEAR BY ROOMS</h3>
      <% for room in @room.nearbys(10) %>
        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.cover_photo(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room %><br/>
              (<%= room.distance.round(2) %> km away)
            </div>
          </div>
        </div>
      <% end %>
    </div>

    </div>

    <!-- RIGHT PANEL -->
    <div class="col-md-4">
      <!-- Reservation form -->
      <%= render 'reservations/form' %>
    </div>
</div>

<script>
  $('#average_rating').raty({
    path: '/assets',
    readOnly: true,
    score: <%= @room.average_rating %>
  });
</script>

app/views/rooms/update.html.erb
<h1>Room#update</h1>
<p>Find me in app/views/room/update.html.erb</p>